### ISSUE TITLE
OkHttp3 Interceptor crash

### ISSUE THREAD

**Issue by juandiana** [facebook/stetho#346]
I just upgraded OkHttp to version 3.0.1 and Stetho to version 1.3.0 (and its corresponding new OkHttp3 network interceptor).

I'm experiencing the following NullPointerException when inspecting HTTP traffic:

```
E/stetho: com.facebook.stetho.inspector.elements.android.DialogFragmentDescriptor.getChildren() emitted a null child at position 0 for element LayoutFragment{3a8b2dd3 #0 id=0x7f0c00dc}
E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
         Process: com.artech.androidbasictest.testgxsalto, PID: 29855
         java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
         at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229)
         at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:143)
         at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:73)
         at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
         at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
         at okhttp3.RealCall.getResponse(RealCall.java:241)
         at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
         at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
         at okhttp3.RealCall.access$100(RealCall.java:30)
         at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
         at java.lang.Thread.run(Thread.java:818)
```

**Comment by jasta** [comment]
This looks like the same issue as with okhttp2, you may have accidentally used a regular interceptor instead of a network interceptor.  I keep forgetting to actually fix this with a proper error message :(

**Comment by juandiana** [comment]
I did notice that there are two methods for adding an interceptor when building an `OkHttpClient` instance. Notice that I actually used the `addNetworkInterceptor` method, as follows:

    mHttpClient = new OkHttpClient.Builder()
            .connectTimeout(CONNECT_TIMEOUT, TimeUnit.SECONDS)
            .readTimeout(READ_TIMEOUT, TimeUnit.SECONDS)
            .addNetworkInterceptor(new StethoInterceptor())
            .build();

**Comment by jasta** [comment]
Hmm, then I'm puzzled.  @swankjesse?

**Comment by swankjesse** [comment]
The interceptor might be returning a null connection after that physical connection has been released back to the pool. Perhaps the response has a `Connection: close` header and the response body is empty? Regardless the fix is pretty easy. I should fix OkHttp to keep a reference to the connection while the interceptor is run so this doesn’t happen.

**Comment by kypeli** [comment]
I am facing the same crash here. 
```
    compile 'com.squareup.okhttp3:okhttp:3.2.0'
    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'
```
Please note that since OkHttp3, you can't add the interceptor with `client.networkInterceptors().add(new StethoInterceptor())` because OkHttp3 is immutable. So you have to use the Builder approach. 

Could the crash be related to this? 

My device is connected since I can use Vysor and debug the app through the same connection, so it's not a connection issue.

**Comment by jasta** [comment]
@kypeli your crash is unrelated.

**Comment by kypeli** [comment]
@jasta Thanks for the clarification. I see the same stack trace or null pointer exception, so must be the same issue as described in this ticket. Hopefully fixed soon :)

**Comment by dave-r12** [comment]
Hello, we've merged in a change that should resolve this that will be going out with OkHttp 3.3.

**Comment by baurine** [comment]
I also face the same crash:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
	at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229)
	at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:143)
	at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:73)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.getResponse(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at cn.pyromusic.pyro.api.RestClient$1.intercept(RestClient.java:69)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

It happens when a http request returns 204 and has no response body. 

I debuged, as above said, it was caused by null connection(). 

I use stetho 1.3.1 and retrofit 2.0 (it depends okhttp 3.2.0)

**Comment by jasta** [comment]
@baurine can you test with okhttp 3.3 to verify that the upstream fix works?  I don't think this is necessarily a Stetho issue.

**Comment by forzajuve** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                            at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:229)
                                                                            at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:143)
                                                                            at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:73)
                                                                            at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
                                                                            at com.youku.laifeng.libcuteroom.http.LFHttpClient$LFInterceptor.intercept(LFHttpClient.java:1311)
                                                                            at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
                                                                            at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
                                                                            at okhttp3.RealCall.getResponse(RealCall.java:241)
                                                                            at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                            at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)




compile 'com.facebook.stetho:stetho:1.3.1'
compile 'com.facebook.stetho:stetho-okhttp3:1.3.1'

OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.connectTimeout(CONNECT_TIME_OUT, TimeUnit.SECONDS);
        builder.writeTimeout(WRITE_TIME_OUT, TimeUnit.SECONDS);
        builder.readTimeout(READ_TIME_OUT, TimeUnit.SECONDS);
        builder.networkInterceptors().add(new StethoInterceptor());
        mOkHttpClient = builder.build();

**Comment by Baleizao** [comment]
@jasta I have the same problem and did some digging. The source of the crash is that `okhttp3.RealCall.connection()` always returns null. This is its current source code in master:

    public Connection connection() {
      return null;
    }

The fix that @swankjesse made for [#2288](https://github.com/square/okhttp/issues/2288) fixes the crash that @baurine saw but doesn't fix the case of `okhttp3.RealCall` being used.

I also noticed that we only need the connection object to compute a hash code that will become the connection ID, so maybe we don't even need a reference to the connection in the first place. Is there a chance we can replace it by something else (e.g. a counter or some random number)?

**Comment by swankjesse** [comment]
Yikes. I’ll fix this one too.

**Comment by swankjesse** [comment]
(Or more specifically, I’ll ask @dave-r12 to fix it!)

**Comment by dave-r12** [comment]
@Baleizao I do not see that RealCall has a connection() method. I think you might be referring to the ApplicationInterceptorChain class? That class handles Application interceptors, which are different than network interceptors (see https://github.com/square/okhttp/wiki/Interceptors). Stetho is using a network interceptor, so that class should not matter.

**Comment by Baleizao** [comment]
Gah... you're absolutely right! I accidentally installed the `StethoInterceptor` as an application interceptor instead of as a network interceptor, hence the crash. Sorry folks! All sorted now.

**Comment by baiiu** [comment]
Yes, it is. use `addNetworkInterceptor` method it is ok.  I have no words to say.

**Comment by baurine** [comment]
@jasta so so sorry, I just remember the thing you asked me to do. but I can't find okhttp 3.3, the latest version is still 3.2.0. I tried `compile 'com.squareup.okhttp3:okhttp:3.3.0-SNAPSHOT'`, but gradle tell me `Failed to resolve: com.squareup.okhttp3:okhttp:3.3.0-SNAPSHOT`. I read the above comments, it seems this bug has already fixed, right?

> @baurine can you test with okhttp 3.3 to verify that the upstream fix works? I don't think this is necessarily a Stetho issue.

**Comment by juandiana** [comment]
@baurine According to OkHttp's README:
> Snapshots of the development version are available in Sonatype's snapshots repository.

So, you just need to add the repository url to your gradle script repositories section.

```
repositories {
    ...
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
}
```

**Comment by baurine** [comment]
@juandiana thank you! it works. Now I used the okhttp 3.3, test again, the crash has not happened again. but my develop environment is not as same as before, I updated the android studio from 1.5 to 2.1. any way, if I meet this bug again, I will report.

**Comment by jasta** [comment]
Can this issue be closed out?  It looks like the thread has settled a bit and okhttp 3.3 is indeed confirmed to fix, yes?

**Comment by fzymek** [comment]
I was using okhttp as transitive dependency from retrofit2 and this crash happened to me as well. After including direct dependency to okhttp:3.4.2 it is no longer happening.

**Comment by tprochazka** [comment]
I have the same problem on Stetho 1.5.0 and OKHttp 3.8.1

```
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
                                                                                    at com.facebook.stetho.okhttp3.StethoInterceptor$OkHttpInspectorResponse.connectionId(StethoInterceptor.java:226)
                                                                                    at com.facebook.stetho.inspector.network.NetworkEventReporterImpl.responseHeadersReceived(NetworkEventReporterImpl.java:145)
                                                                                    at com.facebook.stetho.okhttp3.StethoInterceptor.intercept(StethoInterceptor.java:70)
                                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                    at cz.atomsoft.android.tvprogram.api.ServerConnector$UserAgentInterceptor.intercept(ServerConnector.java:540)
                                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                    at cz.atomsoft.android.tvprogram.api.ServerConnector$RetryInterceptor.intercept(ServerConnector.java:553)
                                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                                    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                                    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                                    at okhttp3.RealCall.execute(RealCall.java:69)
```

**Comment by cristan** [comment]
[A null check](https://github.com/facebook/stetho/commit/59791f8f97f98afa106e63d6e9bc7e51a8211a61) has been committed on master, but no release has been made after 1.5.0 yet.

**Comment by lyew-phunware** [comment]
When are we expecting the null check on master to be updated into a 1.5.1 release? We're blocked using stetho's network feature because of the crash fixed with @cristan's commit.

**Comment by naturalwarren** [comment]
Is your interceptor registered as a network interceptor? #549 provides a better error message when you're incorrectly registered as a vanilla interceptor.

**Comment by jasta** [comment]
We don't actually want folks using StethoInterceptor as an app interceptor (instead of a network interceptor), so we've gone further and are now just throiwng a clear error message to this effect.  See #584.

**Comment by anjinlu** [comment]
App Crashes when the request is cancelled and the interceptor return NULL.

In my code, "Cancelled" exception was caught, return NULL or re-throw the exception cause the app crash.

	public class HttpInterceptor : Java.Lang.Object, IInterceptor {
		public Response Intercept(IInterceptorChain chain) {
			Response response = null;
			try {
				Request request = chain.Request();
				response = chain.Proceed(request);
			} catch (Exception e) {
			}
			return response;
		}
	}
